import "./env";
import { privateKeyToAccount } from "viem/accounts";
import type { Hunt, Player, Spawn } from "@prisma/client";
import { db } from "./db";
import { commitSeed, deriveSeed } from "@/lib/hunt/spawn";

/**
 * A player, with the key that signs for them.
 *
 * Deterministic keys derived from an index: a fixed key per index makes a
 * failing run reproducible, and these are throwaway test keys that never hold
 * anything and never touch a chain.
 */
export interface TestPlayer {
  player: Player;
  privateKey: `0x${string}`;
  address: string;
}

export function testKey(index: number): `0x${string}` {
  return `0x${(index + 1).toString(16).padStart(64, "0")}` as `0x${string}`;
}

export async function makePlayer(index: number): Promise<TestPlayer> {
  const privateKey = testKey(index);
  const address = privateKeyToAccount(privateKey).address.toLowerCase();
  const player = await db.player.create({
    data: { walletAddress: address, displayName: `player-${index}` },
  });
  return { player, privateKey, address };
}

/**
 * A hunt that accepts collects.
 *
 * Defaults are the permissive end of each verifier rule so a test that is not
 * about a rule does not have to restate it. Anything a test IS about is passed
 * in and therefore visible in the test itself.
 */
export function makeHunt(overrides: Partial<Hunt> = {}): Promise<Hunt> {
  return db.hunt.create({
    data: {
      name: "integration hunt",
      active: true,
      spawnEnabled: true,
      maxAccuracyM: 30,
      maxSpeedKmh: 60,
      cooldownSeconds: 0,
      maxClockSkewSeconds: 120,
      // A budget large enough not to be the thing under test unless a test
      // narrows it. Ten MON in wei.
      budgetMonWei: "10000000000000000000",
      spawnMinWei: "1000000000000000",
      spawnMaxWei: "1000000000000000",
      spawnDailyCapWeiPerPlayer: "10000000000000000000",
      budgetCreditWei: "1000000000000000000000",
      ...overrides,
    } as never,
  });
}

/**
 * A collectable spawn sitting at `at`, already on the player's radar.
 *
 * `seedCommit` has to open to `deriveSeed(SPAWN_SEED_SECRET, spawn.id)` or the
 * collect route answers 503 — it will not pay out a spawn whose reveal does not
 * match what it published. The id is generated by the insert, so the commitment
 * is written in a second statement, which is exactly what the route does too.
 */
export async function makeSpawn(args: {
  hunt: Hunt;
  player: Player;
  at: { lat: number; lng: number };
  amountMonWei: string;
  ttlSeconds?: number;
  radiusMeters?: number;
}): Promise<Spawn> {
  const created = await db.spawn.create({
    data: {
      huntId: args.hunt.id,
      playerId: args.player.id,
      lat: args.at.lat,
      lng: args.at.lng,
      radiusMeters: args.radiusMeters ?? 40,
      amountMonWei: args.amountMonWei,
      seedCommit: "placeholder",
      expiresAt: new Date(Date.now() + (args.ttlSeconds ?? 900) * 1000),
    },
  });

  const seed = deriveSeed(process.env.SPAWN_SEED_SECRET!, created.id);
  return db.spawn.update({
    where: { id: created.id },
    data: { seedCommit: commitSeed(seed) },
  });
}

/** Ensure the counter row a conditional UPDATE needs to hit exists. */
export function makePlayerHunt(huntId: string, playerId: string) {
  return db.playerHunt.create({ data: { huntId, playerId } });
}
